-- ADD INDEXES
CREATE UNIQUE INDEX IF NOT EXISTS IDX_FAN_NAME ON fans (name);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_FAN_ID ON fans (id);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_MUSICIAN_NAME ON musicians (name);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_MUSICIAN_ID ON musicians (id);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_PLACE_NAME ON places (name);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_PLACE_ID ON places (id);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_GENRE_NAME ON genres (name);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_GENRE_ID ON genres (id);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_FAV_MUSICIAN_ID ON favorite_musicians (id);
CREATE UNIQUE INDEX IF NOT EXISTS IDX_FAV_PLACE_ID ON favorite_places (id);
